project:
  type: book

book:
  title: "Health Inequalities Book"
  author: "MSDN Collaboration Group"
  date: "last-modified"
  chapters:
    - index.qmd
    - content/intro.qmd
    - content/rural.qmd
    - content/imd.qmd
    - content/summary.qmd
    - references.qmd
    
  repo-url: https://github.com/nhs-r-community/health-inequalities-notebook
  repo-branch: main
  repo-actions: [edit, issue]
    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

